### ISSUE TITLE
Wrong card type identifier

### ISSUE THREAD

**Issue by andradedaniel** [jlorente/php-credit-cards#2]
Hi, 

There are a bug when identify the card type. 
For the same card number the `braintree/credit-card-type` lib identifies one type and this php lib identifies another type. 

To reproduce: 
Card number: 6062826786276634
`braintree/credit-card-type` returns 'Hipercard' type. 
This lib returns 'Maestro' (as image below)  

![image](https://user-images.githubusercontent.com/15149518/204298387-03a0fa64-6354-4efb-aed1-0cfb4f4d896f.png)

Maybe the problem is the `SplPriorityQueue()` in the `getType()` method. 
The `$configResult` is a bool and it is used to define de priority when inserted to the queue.

**Comment by jlorente** [comment]
Thanks @andradedaniel, I will check the issue and upload a solution.

**Comment by jlorente** [comment]
This commit fixes the issue: https://github.com/jlorente/php-credit-cards/commit/ec74c7c9240ddd0c48146408ebadaeefbd0fda90

Sorry for the delay in fixing it.
